# Generated by Django 3.2.16 on 2024-03-26 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('slug', models.SlugField(help_text='Идентификатор страницы для URL; разрешены символы латиницы, цифры, дефис и подчёркивание.', unique=True, verbose_name='Идентификатор')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='ListToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название задачи')),
                ('description', models.TextField(help_text='Добавьте краткое описание задачи', verbose_name='Описание')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('is_ready', models.BooleanField(help_text='Поставьте галочку, чтобы отметитьготовность задачи', verbose_name='Готова')),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='list_todo.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'список задач',
                'verbose_name_plural': 'Списки задач',
                'ordering': ('-add_date',),
            },
        ),
    ]
