# Generated by Django 3.2.16 on 2024-04-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_todo', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listtodo',
            name='ready_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Сделать до: '),
        ),
        migrations.AlterField(
            model_name='listtodo',
            name='is_ready',
            field=models.BooleanField(help_text='Поставьте галочку, чтобы отметить готовность задачи', verbose_name='Готова'),
        ),
    ]
