# Generated by Django 3.2.16 on 2024-05-02 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_todo', '0003_auto_20240402_1752'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listtodo',
            options={'ordering': ('-is_ready', '-add_date'), 'verbose_name': 'список задач', 'verbose_name_plural': 'Списки задач'},
        ),
    ]
